
name: Build APK after pull request in develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  assembleApk:
    name: Generate APK
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  #    - name: Update release version
  #      run: |
  #        latest_release="$(git describe --match 'v[0-9]*\.[0-9]*\.[0-9]*' --abbrev=0 --tags)"
  #        change_to="versionName "\"$latest_release"\"" sed -i "0,/versionName/{s/.*versionName.*/$change_to/}"
  #        app/build.gradle
      - name: Print run id
        run: echo "$github.run_id"
          
          
  slackMessage:
    name: Post message to slack
    runs-on: ubuntu-latest
    needs: assembleApk
    steps:
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: "#android_builds"
          SLACK_USERNAME: "@gustavo"
          SLACK_TITLE: "New Android release"
          SLACK_MESSAGE: "Test"
